### ISSUE TITLE
Unit tests don't cover generated parser

### ISSUE THREAD

**Issue by Victorious3** [neogeny/TatSu#106]
There's one issue with how the unittests run currently. 
There are significant differences between how the parser behaves when running from the generated code and when running in immediate. 
Tatsu's self test doesn't cover all the features that have been added, so for completeness all the other unit tests should run twice.

**Comment by apalala** [comment]
There are no unit tests for nullability, and other facets of leftrec.

The generated Python parser has been the main output of TatSu during it's evolution, so, if something's broken, it is probably in the model parsing.

The project hasn't aimed for unit-test coverage or test first so far, but has rather created a unit test for every bug found. On the spirit of keeping it that way (as complete unit-test coverage is just too much work), I'll close this issue.

**Comment by Victorious3** [comment]
It's still something I'd like to do this eventually.
I did it ad hoc for this one: https://github.com/neogeny/TatSu/blob/master/test/grammar/semantics_test.py#L74
felt a bit unecessary.

Pytest has ways to run them with parameters, I'd simply replace `compile` with a fixture method that either runs on the generated parser or in immediate depending on what mode pytest runs in currently. I wasn't talking about adding new unit tests altogether, just letting the ones that already exist cover both cases.

**Comment by apalala** [comment]
I like your idea of parameterizing the tests.

We should also drop `unittest` in favor of `pytest`, which allows for clearer and more powerful tests. 

Shall we make that change part of this same ticket?

**Comment by apalala** [comment]
https://github.com/neogeny/TatSu/projects/1

**Comment by apalala** [comment]
Hi @Victorious3 ! The generated parser is covered by `bootstrap_test.py`, which cycles generating the bootstrap parser to make sure that the bootstrap parser generates the bootstrap parser.

I copy the last parser generated by the test to `tatsu/bootsrap.py` manually before a release.

What else do we need to do here?

**Comment by apalala** [comment]
There's no proposed course of action for this issue, so I'm closing it now.
