### ISSUE TITLE
Simplify Node and remove AST

### ISSUE THREAD

**Issue by apalala** [neogeny/TatSu#123]
The class `ast/AST` is a `dict/object` that was the first default output of parsers produced by Grako. It is complicated and fragile.

There's no reason why the parser cannot use only `objectmodel.Node`, with a simplified implementation that doesn't do transformations from `AST`. `Node.__str__()` could default to JSON over the `__json__()` representation to keep the documentation mostly unchanged.

Experiments with basing `Node` on `@dataclass` can be found [here](https://github.com/apalala/pglc/blob/master/pglc/model.py).

**Comment by Victorious3** [comment]
I wonder what implications that would have on my project. I have a couple instanceof checks for AST but those are probably not that important. 

Node I ended up extending myself with an `__eq__` for testing. (It doesn't do a true equality check, I consider an empty list or None the same as "attribute does not exist" to make my tests smaller). I also ended up doing something silly that looks like this:
```py
def __value_type(cst):
    return lambda value: cst(ast = value)

def __list_type(cst):
    return lambda *args: cst(ast = list(args))

# ...
__value_types(String, Char, Integer, Float, Boolean, Goto, Unsigned, Word, IdAssign, SizeOf)
__list_types(Array, Body, Identifier, Compare, Program, StructBody, EnumBody, Return)
```
I think you see where this is going. I kinda hate it but it does allow me to do things like this:
```
Integer(4)
Program(
    stmt1,
    stmt2,
    ...
)
Div(
    left = expr
    right = expr
)
```
Usually only the third one is permitted. The first two would be AST if I didn't force them to be Nodes.
Maybe you want to consider this when you redo Node. I collide with the constructor a lot here (I have a separate file with those lambdas that ends up shadowing them), maybe Tatsu could use something else to initialize them and allow for easier usage.

**Comment by apalala** [comment]
This relates to issue #197.

**Comment by apalala** [comment]
I agree that `AST` has had a happy life, and it has matured.

The problem is `Node` and all that model and code generation assumes about it.

I don't like that `grammars.Model` inherits from the too-complicated `objectmodel.Node`.

* there mus be an abstract (an interface) definition of the output of a parse (and the best name for it is `AST`)
* `semantics.ModelBuilderSemantics` will use a pre-defined implementation of the above abstract definition
* walkers (what else?) will work if the user provides a differnt implementation of AST

It's been a long time, but the interesting parts about `Node` and `AST` are implemented and well proven in [python-box](https://pypi.org/project/python-box/).

This piece of code in `ast.AST` has nothing to do with ASTs. It's a quirk of how TatSu parses, so it should be moved to `contexts.ParserContext`:

```python
    def _set(self, key, value, force_list=False):
        key = self._safekey(key)
        previous = self.get(key)

        if previous is None and force_list:
            value = [value]
        elif previous is None:
            pass
        elif is_list(previous):
            value = previous + [value]
        else:
            value = [previous, value]

        super().__setitem__(key, value)
```

TatSu has never required a a third-party library before, but maybe it's time to require something like `python-box`?

**Comment by apalala** [comment]
We move the above `AST` logic to `contexts.ParseContext` here:

```python
    def name_last_node(self, name):
        self.ast[name] = self.last_node

    def add_last_node_to_name(self, name):
        self.ast._setlist(name, self.last_node)
```

(I remember that it was there once)

**Comment by apalala** [comment]
This is too old, and TatSu models already use `@dataclass`.  I'm working with TatSu again, so I'll close this issue. If clearer requirements emerge, there will be a new issue.
