### ISSUE TITLE
Allow the use of tokenizers

### ISSUE THREAD

**Issue by apalala** [neogeny/TatSu#129]
TatSu parsers are currently dependent on the `buffering.Buffer` class. Some languages (like Python) have complex semantics at the lexical level, and some projects have an existing tokenizer (like Python) that they would like to use on a PEG parser.

It should be possible to abstract what a parser is actually requiring from `Buffer` and adapt that to what a tokenizer can offer. It may be required that `pos`, the input position be separate from `LineInfo`, and it could be that some tokenizers have no implementation for `matchre()`.

**Comment by Victorious3** [comment]
Interesting. Not sure if this is related but I've gone ahead and used your suggestion of using `eat_whitespace` and the others to replace my custom preprocessing. That worked out so and so. I ended up having to jerry-rig the Buffer by passing my semantics instance, since an open paren would start to ignore newlines. I wonder if this could be solved in a better way.

**Comment by apalala** [comment]
Take a look at the _"magic"_ I've done in [pglc](https://github.com/apalala/pglc/blob/master/pglc/pythonc/semantics.py) to parse Python at the lexical level. It is ugly and no-obvious.

Since Python already has a tokenizer, I have an excuse to support that in TatSu.

But before I do that, I will try to implement the lexical semantics with `eat_whitespace()` and friends, to understand the limits better.

One of the reasons for PEG is that some interesting languages require that the parser guides the tokenizer, as when there are languages within languages. A typical example is Python `f-strings`, in which complete Python expressions (that must be parsed) may be embedded in what what otherwise is a string.

**Comment by Victorious3** [comment]
I solved a lot of the other "context sensitivity" by inflating the grammar in various ways. I've started to think about using m4 or something silly to get the size down a bit. I have four different if statements for instance, depending on whether its a static if, one of those inside of a struct, or an enum, or if it's a normal if statement. They allow different contents while the construct itself works in the exact same way:
```
struct {
    #if cond {
        a: int
    } else {
        a: double
    }
}
```
```
enum {
    #if cond {
        A = 1
    } else {
        A = 2
    }
}
```
```
#if cond {
    // Arbitrary code here
}
```
```
if cond {
    // Arbitrary code here
}
```
Another interesting case I have is named parameters:
`foo(a = 2)`
Unlike python my assignments are actually expressions, which creates a situation here where I have to enter the expression grammar just after the precedence level of the assignment.
`foo(a = b = 2)` is disallowed.

I haven't really figured out when having semantic actions is the right way to go or when messing with the grammar is. So far I've mostly leaned towards the latter when I could pull it off.

Here's my current version if you're curious: https://gist.github.com/Victorious3/9e8b9916a2f882227601d5bc7c6bc363
