### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by sidmani** [neogeny/TatSu#142]
I get a warning when running the Tatsu parser:
`
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
`
I can write a pull request to fix this, if necessary.

**Comment by apalala** [comment]
Which version of Python are you using?

A pull request would be great!

**Comment by sidmani** [comment]
I'm using python 3.7.4. I cloned the tatsu repo and ran the tests, but the warning didn't come up under the same python, even after removing the lines in tox.ini that suppress pytest warnings. In my project, the issue is listed as being in `tatsu/grammars.py:6`.

**Comment by apalala** [comment]
I forgot to ask, Which version of TatSu?

The latest published version is compatible with Python 2.7, and doesn't use any porting libraries like `six`.

A patch should consist of surrounding the import of the ABC with an `if PY3:`.

**Comment by sidmani** [comment]
Tatsu 4.4.0. It looks to me like the problem is fixed in master, but just hasn't been released yet- no additional patch necessary.

**Comment by apalala** [comment]
Culd you write a pull request with a unit test that proves that the problem is gone? I'd do a bug-fix release.

**Comment by sidmani** [comment]
PR submitted!
