### ISSUE TITLE
[DOC] Is the Warning in Left Recursion still valid?

### ISSUE THREAD

**Issue by okomarov** [neogeny/TatSu#156]
The docs in [Left Recursion](https://tatsu.readthedocs.io/en/stable/left_recursion.html) say that:
> The following grammar is correct, but it will not work if the start rule is changed to `start = mul ;`.

I tried to change the grammar rule to `start = mul ;` as suggested and could still parse `'a * b * c'`:
```
# AST
(   ('a', '*', 'b'),
    '*',
    'c')
```

What kind of failure should I expect?

### To reproduce

test.tatsu:
```
start = mul ;

expr = mul | identifier ;

mul = expr '*' identifier ;

identifier = /\w+/ ;
```

test.py:
```
from pprint import pprint

import tatsu


def simple_parse():
    with open('test.tatsu') as f:
        grammar = f.read()
    parser = tatsu.compile(grammar)

    ast = parser.parse('a * b * c')

    print('# AST')
    pprint(ast, width=20, indent=4)

if __name__ == '__main__':
    simple_parse()
```
then from command line `python test.py`.

**Comment by apalala** [comment]
Left recursion was reimplemented, and now produces correct parses for all test cases. The documentation must be updated. Associativity when there is both left and right recursion is still a pending topic.

Thanks for the catch!
