### ISSUE TITLE
usage example: grab all capitals in xml

### ISSUE THREAD

**Issue by nicolasessisbreton** [neogeny/TatSu#165]
What would be the approach to grab all the capitals in the xml below?

```
<world>

  <country>
    <name>us</name>

    <city>
      <name>washington</name>
      <capital>yes</capital>
    </city>

    <city>
      <name>new york</name>
      <capital>no</capital>
    </city>

  </country>

  ... many more countries ...

</world>
```

Here are some attempts.

approach #1
- use a grammar to define opening and end tag semantics
- walk the generated AST, find the answer by using lots of if-statements
=> all the if-statement make the code fragile to change

approach #2
- make a very detailed grammar that captures all the xml tag possibilities
- applies a class or a function on the desired semantic element of the grammar
=> too long to do

are there other ways?

This example is simplified, the condition on the element to grab could be arbitrarily complex.
(think XPath)
XPath is nice but has the same problem then approach #1 (fragile).
Handling the task with a grammar gives a maintainable set of complex extractors.
(define only the bit needing extraction, handling of massive xml,...)

**Comment by Victorious3** [comment]
I'd use an existing xml parser for this. What's wrong with using XPath? It seems to be the right tool for the job.
Besides, questions like this belong on stackoverflow with the [tatsu] tag.
