### ISSUE TITLE
Order of choices not respected: model versus file parser

### ISSUE THREAD

**Issue by okomarov** [neogeny/TatSu#166]
### Setup
On Python 3.8 TatSu 5.5 possibly related to #160

The following grammar:
```
@@grammar :: ORDER
alphabet = a b others $ ;

a = 'a' ;
b = 'b' ;
others = 'c' | 'd' | 'e' | 'f' |'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o';
```

compiled with:
```
tatsu grammar.ebnf -o parser.py
```
### The issue
**The order of the choices in `others` is not preserved if we use the parser compiled on-the-fly (in memory)**:
```
# MEMORY
(1:3) expecting one of {'g' 'h' 'i' 'o' 'j' 'e' 'd' 'c' 'k' 'f' 'm' 'l' 'n'} :
a b
  ^
others
alphabet 


# PARSER
(1:3) expecting one of: c d e f g h i j k l m n o :
a b
  ^
others
alphabet
```

Line https://github.com/neogeny/TatSu/blob/fc9caacd1f08a645a37376ff20badc18aca62b59/tatsu/grammars.py#L137 is the specific issue for the lookahead of choices for the in-memory model. However the issue might be bigger, since `set()` is used a bit everywhere. An `OrderedSet` should solve the issues.

### How to reproduce
You can reproduce the above with `main.py`:
```
import tatsu


def main():
    text_to_parse = 'a b'

    print('# MEMORY')
    with open('grammar.ebnf') as f:
        grammar = f.read()
    parser = tatsu.compile(grammar)
    try:
        ast = parser.parse(text_to_parse)
    except Exception as e:
        first_error = e
    print(first_error, '\n\n')

    print('# PARSER')
    from parser import ORDERParser

    parser = ORDERParser()
    try:
        ast = parser.parse(text_to_parse, rule_name='alphabet')
    except Exception as e:
        second_error = e
    print(second_error)

if __name__ == '__main__':
    main()
```

### Why relevant
Differences between a parser compiled on-the-fly and a parser compiled to file will generate confusion when developing the grammar. It's convenient to have a parser compiled directly from the grammar as you can edit one file, and then run a set of tests against the modified grammar. 

However, results to be different as also mentioned in #160. Currently the solution seems to always compile to file and load the generated parser class from that.

**Comment by apalala** [comment]
I'll leave this open to resolve the difference.

But this error reporting has nothing to do with the actual parsing. The lookahead sets are computed to provide more meaningful error reports, but they are not part of the parsing or of parser generation.

**Comment by apalala** [comment]
The error message is fixes in the latest version on `master`.
