### ISSUE TITLE
Ignorecase needs uppercase keywords when reserving

### ISSUE THREAD

**Issue by okomarov** [neogeny/TatSu#167]
Reserving keywords and ignoring case does not work as expected:

```
@@ignorecase :: True
@@keyword :: if

@name
rule = /\w+/  if_exp $ ;

if_exp = 'if' /\d/ ;
```
**The 'if' is parsed as the rule while it should error.**

This is because in [contexts.py](https://github.com/neogeny/TatSu/blob/master/tatsu/contexts.py), you should apply either `upper` (or `lower`) to both name and keywords:
```
def _check_name(self, name=None):
    if name is None:
        name = str(self.last_node)
    if self.ignorecase or self._tokenizer.ignorecase:
        name = name.upper()
    if name in self.keywords:
        raise FailedKeywordSemantics('"%s" is a reserved word' % name)
```

**Comment by apalala** [comment]
I note a misunderstanding about the use of pattern matches. Pa pattern match _will not_ advance the input, so the above grammar should fail to parse expected in put like "hello if 1" .
