### ISSUE TITLE
Deprecation warning on python 3.7 

### ISSUE THREAD

**Issue by plankthom** [neogeny/TatSu#168]
https://github.com/neogeny/TatSu/blob/79dd46c2f455876cb10b85f47184588953398c8f/tatsu/grammars.py#L6

(from the 4.0 branch) raises a deprecation warning
```
.../lib/python3.7/site-packages/tatsu/grammars.py:6
  .../lib/python3.7/site-packages/tatsu/grammars.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import defaultdict, Mapping
```

As the `5+` versions are not supported on 3.7,  the import should probably be fixed for python 3 runtimes ...?

**Comment by tirkarthi** [comment]
Seems to be fixed with https://github.com/neogeny/TatSu/issues/153 and https://github.com/neogeny/TatSu/commit/a4fd84a2785fb0820ed65fe80ebd768458643b66

**Comment by apalala** [comment]
This was fixed.
