### ISSUE TITLE
Argument of the exceptions.FailedToken exception

### ISSUE THREAD

**Issue by Karel-Tavernier** [neogeny/TatSu#169]
I am writing a syntax checker for a file format. The goal is to have decent reporting of syntax errors. The Failed.Toke exception is important for that. Now this exception has a pretty __str__(), so it prints nicely, but one would like to control what is output.  The return argument is an empty tuple, which is not helpful. It would be handy if it would return to constituent elements of the exception, and possibly more useful information. This would also fit what is written in the python docs: "...the exception instance defines __str__() so the arguments can be printed directly..."

Summary: let the FailedToken exception return a tuple with the constituent parts of what it prints, and maybe more.

**Comment by Victorious3** [comment]
You can catch a FailedToken exception and use its values directly. It has a reference to the tokenizer (which you can probe for additional data), a message, a position and a stack trace.

**Comment by Karel-Tavernier** [comment]
What exactly do you mean by 'use its values directly'?

**Comment by Victorious3** [comment]
Well you don't need to call `__str__`:
```python
model = compile(grammar)
try:
    result = model.parse("input")
except FailedToken as e:
    print(e.message)
    print(e.stack)
    ...
```

**Comment by Karel-Tavernier** [comment]
Thx. I will check this out.

Wkr,
Karel Tavernier

________________________________
