### ISSUE TITLE
Does TatSu enable changing grammar dynamically?

### ISSUE THREAD

**Issue by pressureless** [neogeny/TatSu#170]
After TatSu has compiled the grammar, how can we add new rules or new keywords to the grammar?
Recompiling the whole grammar file is too slow. Can we do it dynamically?
I have checked the documentation but haven't found any clues.
Any suggestion will be helpful. Thanks!

**Comment by Victorious3** [comment]
There is currently no supported way to do this.

You'd have to mess with the internals of TatSu. It's certainly achievable but I wouldn't recommend it. Have a look around `tatsu/grammars.py`. You'd have to essentially modify the rules of an already compiled grammar and "merge" them with the rules of a new compiled grammar. You could also modify single rules like this.

**Comment by pressureless** [comment]
Thanks for your reply!
I finally use ```to_python_sourcecode``` and ```to_python_model``` to save the parser class and modify it directly
