### ISSUE TITLE
Support for Non-Greedy Regex?

### ISSUE THREAD

**Issue by flosincapite** [neogeny/TatSu#173]
Let's say I have a grammar like

```
GRAMMAR = '''
start = {expression}+;
expression = 
 | class_a:?'<.*>'
 | class_b:?'.+?';
"""
```

In theory, I'd like this to partition my input into `class_a` (anything enclosed in angle brackets) and `class_b` (any sequence of characters not so enclosed).

However, it seems that non-greedy search only consumes one character at a time:

```
tatsu.parse(GRAMMAR, """<class_a>
abc<class_a>""")
```

produces 

```
[{'class_a': '<class_a>'}, {'class_b': 'a'}, {'class_b': 'b'}, {'class_b': 'c'}, {'class_a': '<class_a>'}]
```

when I'd expect 

```
[{'class_a': '<class_a>'}, {'class_b': 'abc'}, {'class_a': '<class_a>'}]
```

Is this a bug? A feature? Or is there support for non-greedy matching somewhere? 

Thanks!

**Comment by Victorious3** [comment]
A non greedy regex matches your character as few times as possible, so naturally you would get matches of single characters. This is working as expected.
A working version could be this:
```
start = {expression}+;
expression = 
| class_a: /<.+?>/
| class_b: /[^<]+/;
```
It also uses a non greedy regex.

**Comment by flosincapite** [comment]
Thanks!
