### ISSUE TITLE
Closure of named element does not produce list for single match

### ISSUE THREAD

**Issue by adam-trhon** [neogeny/TatSu#176]
According to documentation, _The AST returned for a closure is always a list._

However, this code:

    #!/usr/bin/env python3

    import tatsu

    def test_named_element_closure_produces_array():

        GRAMMAR = """
            start = { statements:statement } $ ;
            statement = /[a-z]+;/ ;
        """

        parser = tatsu.compile(GRAMMAR)
        parsed = parser.parse("asdf;")
        assert len(parsed['statements']) == 1

fails under pytest with:

    >       assert len(parsed['statements']) == 1
    E       AssertionError: assert 5 == 1
    E        +  where 5 = len('asdf;')

And when I print the `parsed` variable, I get

    {'statements': 'asdf;'}

The error can be fixed by redefining the grammar this way:

        GRAMMAR = """
            start = { statements+:statement } $ ;
            statement = /[a-z]+;/ ;
        """

If this is the right approach, closure does not _always_ produce a list and documentation should be updated.

**Comment by Victorious3** [comment]
I believe you mean  `start = statements: { statement } $;`. 
I would expect your code to yield something like `[{'statements': 'asdf;'}]` which is what you get when you introduce another rule like this:
```
start = { statements } $ ;
statements = statements: statement;
statement = /[a-z]+;/ ;
```
Closures of named elements don*t seem to be well defined at the moment.

**Comment by apalala** [comment]
As @Victorious3 says, to get the list for the closure you need:

```
start = statements: { statement } $;
``` 

There are historical reasons why this will produce a `list` if there is more than one match: 

```
{ statements:statement } 
```

There's no argument to change that behavior, so it's best to keep it for backwards compatibility.
