### ISSUE TITLE
determine leftrec rules through lookahead

### ISSUE THREAD

**Issue by apalala** [neogeny/TatSu#196]
The `_lookahead()` feature of `grammars.Model` includes references to `follow`  elements that are rule references.

It is provable that a rule is recursive if `rule.name in rule.lookahead()`.

Using those features would simplify TatSu's handling of left recursion.

**Comment by apalala** [comment]
@Victorious3 Care to opinionate?

**Comment by Victorious3** [comment]
I don't quite remember how leftrec works, its been two years after all since I've implemented that.

**Comment by apalala** [comment]
There's a [nice implementation in `pegen`](https://github.com/python/cpython/blob/9a50ef43e42ee32450a81ce13ed5a0729d3b84e8/Tools/peg_generator/pegen/parser_generator.py#L164), but I doubt it's less complex than the one you wrote.

**Comment by apalala** [comment]
Lookaheads are not enough. See `pegen` for the need for strongly connected-arguments.
