### ISSUE TITLE
Implement __eq__ for Node

### ISSUE THREAD

**Issue by Victorious3** [neogeny/TatSu#197]
I'm currently doing this in my project to test the resulting parse by extending Node and using that as a base class.
I believe TatSu could provide a default implementation for this.

**Comment by apalala** [comment]
Go ahead, @Victorious3. 

This relates to #123, but we can use your findings when we get there.

In fact, why don't you take care of #123 making `Node` and the code-generator's output for models be dataclasses?

The way to avoid the name collisions reported in other issues is to make the `children` etc. functionality be on standalone functions.

**Comment by apalala** [comment]
After working on some simplifications on `Node`, I think that the task here is to skip `_parent`, `_ast`, and `ast`  in a `__dict__`. comparison, like as provided by `Node._pubdict`.

**Comment by apalala** [comment]
An  `objectmodel.Node` represents a unique position in the input source code, so equality should be the default (by address or `id()`).

The use cases I've seen so far only require that `Node` is hashable, and that can be had with:

```python
def __hash__(self):
    return id(self)
```
