### ISSUE TITLE
v5.6.1 breaks grammars that rely on names in rules always producing an AST

### ISSUE THREAD

**Issue by StephenTyler** [neogeny/TatSu#199]
I have the following parser element:

```
flist
	=
	'(' ~ ','.{ e+:statement }* ')' ~
	;

```
And in my python code:

```
def flist(self, ast):
        value = ast.get('e', [])
        return value

```
Under Tatsu 5.5.x, def flist always received a dict, and the code worked.

Under Tatsu 5.6.x, if "e" is empty, ast is a tuple, and the code breaks.  If "e" is non-empty, ast is a dict.

So I now sometimes get this error message:
```
Traceback (most recent call last):
    ....
    value = ast.get('e', [])
AttributeError: 'tuple' object has no attribute 'get'

```
In another case, my code received ast=[] when it was expecting ast={}.

It seems that in v5.6.x, the type of ast can be list, tuple or dict, while in v5.5.x, the type of ast was always dict.

To avoid mountains of type checking, the type of AST should always be returned as a dict, regardless of whether it is empty or missing named items.

**Comment by apalala** [comment]
Thanks for reporting this issue, @StephenTyler! 

v5.5.0 and v5.0.0 had several important bugs, and fixing them may have impacted programs that relied on the buggy behavior.

Could you try changing the grammar to this?

```
flist
	=
	'(' ~ ','. e:{statement }* ')' ~
	;
```

The problem you're having and the bug that was fixed is that in the case below the parser should _not_ return an `AST` if the second option matches.

```
flist
	=
	'(' ~ ','.{ e+:statement }* ')' ~
        |
        int
	;
```

So, your grammar was relying on TatSu behavior that the maintainer considered incorrect.

A final fix for this would require that `AST` creation is done per option in a choice, and not per rule. Doing that will not be so difficult after the latest refactorings.

I'll keep this ticket open to remind me of the issue (please don't mind that I change the title).

**Comment by apalala** [comment]
cc @Victorious3

**Comment by apalala** [comment]
If you have the typical grammar for mathematical expressions:

```
start = e;

e = t + e | t;

...etc
```
The expected output for an input of `1` is `1`, and not the three of AST with all the possible names present while doing the parse.

**Comment by StephenTyler** [comment]
But should the expression:

`e = t + d:c | t;
`

return a dict sometimes, and an atom at other times, depending upon if named item "d" is present?  Or should the returned AST always be a dict?  If the type of the returned AST varies, then to test if "d" is present, you need to write:

`if isinstance(ast, dict) and 'd' in ast:`

which is clumsy and error prone (if the check is omited it may fail on very rare input) instead of the code suggested in the documentation:

`ast['d']`

**Comment by apalala** [comment]
> eturn a dict sometimes, and an atom at other times, depending upon if named item "d" is present?

Yes. Exactly. That's the behavior required for building a parser for, say, Java.

**Comment by apalala** [comment]
I'll close this ticket and open a new one with the issue that actually needs to be fixed.
