### ISSUE TITLE
all names in the successful option should be present in the  AST

### ISSUE THREAD

**Issue by apalala** [neogeny/TatSu#202]
related to #199

Given the grammar below, users expect if the first option in the choice for `expr_range` parses, then both `from` and `to` will be present in the resulting AST, and that is not the current behavior in TatSu.  Some matching strings are "2 .. 9", "2 ..", ".. 9", and "..", and TatSu will only include the names that matched, so the AST for ".." will be `".."`, which is incorrect.

```ebnf
start = expr_range ;

expr_range =
    | [from: expr] '..' [to: expr]
    | expr
    ;

expr =
    /[\d]+/
;
```

cc @Victorious3

**Comment by StephenTyler** [comment]
Under v5.5.0, for the above expr_range parser, input => ast is:

```
'1 .. 2' => {'from_': '1', 'to': '2', 'parseinfo': [None, 'expr_range', 0, 6, 0, 1]}
'1 ..' => {'from_': '1', 'to': None, 'parseinfo': [None, 'expr_range', 0, 4, 0, 1]}
'.. 2' => {'to': '2', 'from_': None, 'parseinfo': [None, 'expr_range', 0, 4, 0, 1]}
'2' => {'from_': None, 'to': None, 'parseinfo': [None, 'expr_range', 0, 1, 0, 1]}
'..' => {'from_': None, 'to': None, 'parseinfo': [None, 'expr_range', 0, 2, 0, 1]}
```

Under v.5.6.1, we get:

```
'1 .. 2' => {'from_': '1', 'to': '2', 'parseinfo': [None, 'expr_range', 0, 6, 0, 1]}
'1 ..' => {'from_': '1', 'to': None, 'parseinfo': [None, 'expr_range', 0, 4, 0, 1]}
'.. 2' => {'from_': None, 'to': '2', 'parseinfo': [None, 'expr_range', 0, 4, 0, 1]}
'2' => '2'
'..' => '..'
```

So there are two different input scenarios ['..' and '2'] that generate AST that is not a dict.

Under v5.5.0, a parser writer could write if ast['to'] safely without causing errors regardless of the input.  If any component has a name, all components that are required should be named.  So the second line should be written `| to:expr` if the parser is used with v.5.5.0.

Under v5.6.1, the ast is sometimes a dict, and sometimes not.  Before checking ast['to'] it is necessary to confirm ast is a dict, and 'to' is an element.

What behaviour is expected according to the documentation?  (I think v.5.5.0's behaviour)
What behaviour is expected according to the code authors?
What behaviour is easiest for parser writers to handle? (I think v.5.5.0's behaviour as no type checking is required)
Is this change disclosed in the change notes? (No).

**Comment by apalala** [comment]
The traditional behavior is the one in 5.6.1. In 5.5.0 the rule would output an AST with names even if the second option succeeded. For grammar writers the solution for the wanted behavior is the one mentioned:

```
expr_range =
    | from:[expr] '..' to:[expr]
    | expr
    ;
```

That said, the expected behavior is that _all_ names mentioned in the successful option are returned. This issue is a reminder to do the work (which implies names being defined by option and not by rule). See #201.

**Comment by apalala** [comment]
#201 is done, @StephenTyler. Would you please test that version using the [branch](https://github.com/neogeny/TatSu/tree/option_defines)?

**Comment by StephenTyler** [comment]
I'm sorry, but I get an error when I try to install that branch:

```
$ git clone https://github.com/neogeny/TatSu.git -b option_defines
$ pip install TatSu -f -e TatSu/
Processing ./TatSu
    ERROR: Command errored out with exit status 1:
...
      File "/private/var/folders/c0/sqsr79vs6w5751k7702_s5s00000gn/T/pip-req-build-lgdykvo5/tatsu/synth.py", line 3, in <module>
        __REGISTRY: dict[str, Any] = vars()
    TypeError: 'type' object is not subscriptable

```

When I repeat with other branches, it works for me.  Sorry, I'm only a novice at installing packages via branches.

**Comment by Victorious3** [comment]
@StephenTyler I think it requires python 3.9 by now

**Comment by StephenTyler** [comment]
With Python 3.9.2, on the schema:

```
@@grammar::TEST

start = expr_range ;

expr_range =
    | [from: expr] '..' [to: expr]
    | [addl: expr] '+' [addr: expr]
    | expr
    ;

expr =
    /[\d]+/

```

version option_defines:

```
'1 .. 2' => {'from_': '1', 'to': '2'}
'1 ..' => {'from_': '1', 'to': None}
'.. 2' => {'to': '2', 'from_': None}
'2' => '2'
'..' => '..'
'1 + 2' => {'addl': '1', 'addr': '2'}

```
version v5.6.1:

```
'1 .. 2' => {'addl': None, 'addr': None, 'from_': '1', 'to': '2', 'parseinfo': [None, 'expr_range', 0, 6, 0, 1]}
'1 ..' => {'addl': None, 'addr': None, 'from_': '1', 'to': None, 'parseinfo': [None, 'expr_range', 0, 4, 0, 1]}
'.. 2' => {'addl': None, 'addr': None, 'from_': None, 'to': '2', 'parseinfo': [None, 'expr_range', 0, 4, 0, 1]}
'2' => '2'
'..' => '..'
'1 + 2' => {'addl': '1', 'addr': '2', 'from_': None, 'to': None, 'parseinfo': [None, 'expr_range', 0, 5, 0, 1]}
```

version v5.5.0:

```
'1 .. 2' => {'from_': '1', 'to': '2', 'addl': None, 'addr': None, 'parseinfo': [None, 'expr_range', 0, 6, 0, 1]}
'1 ..' => {'from_': '1', 'addl': None, 'addr': None, 'to': None, 'parseinfo': [None, 'expr_range', 0, 4, 0, 1]}
'.. 2' => {'to': '2', 'addl': None, 'addr': None, 'from_': None, 'parseinfo': [None, 'expr_range', 0, 4, 0, 1]}
'2' => {'addl': None, 'addr': None, 'from_': None, 'to': None, 'parseinfo': [None, 'expr_range', 0, 1, 0, 1]}
'..' => {'addl': None, 'addr': None, 'from_': None, 'to': None, 'parseinfo': [None, 'expr_range', 0, 2, 0, 1]}
'1 + 2' => {'addl': '1', 'addr': '2', 'from_': None, 'to': None, 'parseinfo': [None, 'expr_range', 0, 5, 0, 1]}

```

Under option_defines, the behaviour of `ast['to']` is fairly complex:

- It succeeds if that named entity is a match.
- It returns None if that named entity is not a match, but other named entities on that path matched.
- It returns a TypeError, if the path matches but none of the named entities match.
- It returns a KeyError, if another path with named entities was matched.
- It returns a TyperError if another path matches and that path has no matching names.

If I was given the choice, I would prefer v5.5.0  - `ast['to']` returns the value if matched, otherwise None.  It never throws a KeyError or a TypeError.  No type checking is required.

**Comment by apalala** [comment]
As I mentioned before, the v5.6.1 behavior is the one grammar writers expect:

```
expre =
    | left:expre op:'*' right:expre
    | left:expre op:'+' right:expre
    | literal
```
The result should be the result of `literal` when it matches, and it will not be an `AST` or `dict`, so `left`, `op`, and `right` will not be available.
