### ISSUE TITLE
Breaking changes not in documentation: buffer name change, lists -> tuples

### ISSUE THREAD

**Issue by zmbc** [neogeny/TatSu#215]
Somewhere between 4.4.0 and 5.6.1, the two versions I was able to test ([possibly intentional, but 5.0.0 is not on PyPI](https://pypi.org/project/tatsu/#history)), two breaking changes were introduced that I did not see mentioned.

1. The ParseInfo `buffer` attribute became `tokenizer`.
2. The values in the parse tree for successive literals (e.g. `my rule = "string" "string" "string";`) changed from lists to tuples.

These should be added to the changelog as well as the Grako compatibility page (which, by the way, is awesome -- I was able to upgrade from Grako very easily, kudos!)

**Comment by apalala** [comment]
I will tend to this.

Do you have an idea about which part of the documentation should be updated?

**Comment by apalala** [comment]
I'm sure I solved this. I don't know why Github didn't pick it up.
