### ISSUE TITLE
parseinfo does not provide useful information for inclusions

### ISSUE THREAD

**Issue by commonism** [neogeny/TatSu#217]
For file inclusions it would be nice if parseinfo could be used to get information about the inclusions file:line and the real source file as well.
I'm looking for a list such as [filename:line] where [-1] is the file itself and [0] is the root, so the real origin file can be tracked.

related: https://stackoverflow.com/questions/56869014/how-to-build-preprocessor-solution-with-tatsu

**Comment by apalala** [comment]
This is solved by `buffering.Buffer.line_index(self, start=0, end=None)`.
