### ISSUE TITLE
AST type changes from dict to tuple based on presence of optional content

### ISSUE THREAD

**Issue by fizbin** [neogeny/TatSu#219]
Consider this grammar:
```
@@grammar :: Test

start = parens:paren_thing;
paren_thing = '(' [ internals:iternal_list ] ')';
iternal_list = @+:ident { ',' @+:ident }* ;
ident = IDENT ;
IDENT = /[A-Za-z]\w*/;
```
Now consider what the strings "`(R)`" and "`()`" parse to with this grammar. (I'm using the JSON representation of the AST)

In TatSu 4.2.5 and TatSu 5.6.1, the first string "`(R)`" parses to `{"parens": {"internals": [ "R" ] } }`

In TatSu 4.2.5 the string "`()`" parses to `{"parens": {"internals": null } }`

In TatSu 5.6.1 the string "`()`" parses to `{"parens": [ "(", ")" ]}`

This makes it extra difficult to write code that handles both cases because the shape of the "parens" value changes simply based on whether an optional element is there, from a `dict` to a `tuple`. This is a surprising incompatibility with older versions of TatSu. Is there any clean way to force the `paren_thing` rule to always return a dictionary?

I guess I could put an extra name on the open or close paren, like:
```
paren_thing = '(' [ internals:iternal_list ] dummy:')';
```
but I'd rather not have to work around this bug.

**Comment by fizbin** [comment]
The weirdness gets worse!

Imagine changing the definition of `paren_thing` to this to
```
paren_thing = '(' [ @+:ident { ',' @+:ident }* ] ')';
```
so that the AST for `paren_thing` is just a list of identifiers.

Then in TatSu 4.2.5 we have that `(R)` parses to `{"parens": ["R"]}` and `()` parses to `{"parens": []}`, as expected.

But in TatSu 5.6.1 we have that `(R)` parses to `{"parens": ["R"]}` and `()` parses to `{"parens": ["(", ")"]}`!

Most surprising.

**Comment by apalala** [comment]
I'll shortly have time to look into these issues.

For now, the solution seems to be:

```
paren_thing = '('  internals:[iternal_list ] ')';
```

**Comment by fizbin** [comment]
We've worked around it with this pattern:

```
paren_thing = '(' internals:( internal_list | () ) ')' ;
```

And we also discovered a similar non-intuitive quirk that affects both 4.2.5 and 5.6.1:

Instead of:
```
stuff = '[' [ @+:ident { ',' @+:ident } ] ']' ;
```
We now do:
```
stuff = '[' ( @+:ident { ',' @+:ident } | @:{} ) ']' ;
```

**Comment by fizbin** [comment]
The rule we've applied to our grammar is "if any path through the grammar uses a `:`, then every path through the grammar must use `:`"; this principle seems to be overly conservative though, since a rule like this *doesn't* seem to exhibit any non-intuitive behavior:
```
thing = '(' [ internal1:internal_one ] [ internal2:internal_two ] ')'
```
(That is, parsing the string `()` still results in a dict-type AST)

**Comment by apalala** [comment]
> stuff = '[' [ @+:ident { ',' @+:ident }* ] ']' ;

The effect of naming within optionals is consistent with the historical semantics of TatSu. The change that tried to have all names in the rule be present broke the semantics because it recovered the names in all choices. That means that the 4.5 series of releases was broken.

I wont close this issue because there is a PR #201 tries to recover all names _in the successful choice_. Please note the lack of follow up to this issue by other TatSu users. The semantics in the latest release are correct, and PR #201 may improve them. 

For the effect you want, the rule above may be rewritten as:

```
stuff = '['  @:','.{ident}* ']' ;
```

The above will always return a list.

**Comment by apalala** [comment]
Overridden by #201
