### ISSUE TITLE
Regex for strings

### ISSUE THREAD

**Issue by alakeev** [neogeny/TatSu#233]
I wanted to be able to parse strings in my grammar so found this in the grammar of Tatsu itself:
```                                                                                           
STRING                                                                                    
    =                                                                                      
    | '"' ~ @:/([^"\n]|\\"|\\\\)*/ '"' ~                                                   
    | "'" ~ @:/([^'\n]|\\'|\\\\)*/ "'" ~
;
```
I've implemented it like this:
```
string = value:stregex;
                                                                                           
stregex                                                                                    
    =                                                                                      
    | '"' ~ @:/([^"\n]|\\"|\\\\)*/ '"' ~                                                   
    | "'" ~ @:/([^'\n]|\\'|\\\\)*/ "'" ~
;
```
However, for some reason it did not work as I thought it supposed to (I might be wrong).
If I tried to parse smth like this: r' ... "\"  ...  '  (which is ' ...  "\" ...'. I'm showing in raw strings not to make a mess) it did not throw a error or anything, instead it handled the string as if it was correct. However, it is not closed since last quote is escaped. Moreover, the following examples did NOT work, though I think they should have:
- `r' ...  "\""  ...  '`
- `r' ...  "\\\""  ...  '`

Same applied to single quoted strings
So I've found a fix for it, however I don't understand why does it help:
```
string = value:stregex;                                                                                           
stregex                                                                                    
    =                                                                                      
    | '"' ~ @:/(\\\\|\\"|[^"\n])*/ '"' ~                                                   
    | "'" ~ @:/(\\\\|\\'|[^'\n])*/ "'" ~; # order of allowed sequences matters          
```
It seems like changing the order does help or at least I haven't found any problematic case.
So I tried to reproduce this bug in grammar file itself, just to make sure that it is not my particular mistake:
Base case:
```
g = tatsu.compile('start = "a" "a" $;')
g.parse("a a")
success
```
Double backslash case:
```
g = tatsu.compile('start = "a\\"a" "a" $;')
Doesn't compile - FailedCut: (1:21) expecting '"' : start = "a"a" "a" $;
```

Double backslash case twice:
```
g = tatsu.compile('start = "a\\"a" "a\\"a" $;')
Doesn't compile - Unknown rules, no parser generated: a
```
Single raw backslash case:
```
g = tatsu.compile(r'start = "a\"a" "a" $;')
Doesn't compile - FailedCut: (1:21) expecting '"' : start = "a\"a" "a" $;
```

Single raw backslash case twice:
```
g = tatsu.compile(r'start = "a\"a" "\"a" $;')
Doesn't compile - FailedToken: (1:17) expecting '.{' : start = "a\"a" "\"a" $;
```
Double backslash all cases:
It's getting quite long, they all failed.

# Finally the question
Is this behavior normal and expected by authors? I could be just making syntax mistake...
If it's not, probably a good candidate to a bugfix. Though I haven't researched it enough to propose anything

**Comment by apalala** [comment]
The intention has always been that TatSu will consume valid Python strings, but the way there has been full of bumps (like in the transition to Python 3.x unicode).

A pull request would be welcome, even if it only consists of unit tests aimed at improving the current behavior.

**Comment by apalala** [comment]
Also, I think that it's better not to copy stuff from TatSu's grammar, because there's legacy stuff there that other parts of the package know how to deal with.

It's better to stick to what the current documentation says.

**Comment by apalala** [comment]
Closing, as this should have been a question on [[tatsu]](https://stackoverflow.com/questions/tagged/tatsu)
