### ISSUE TITLE
Value of ignorecase gets lost

### ISSUE THREAD

**Issue by paulhoule** [neogeny/TatSu#26]
If I use the @@ignorecase directive in the EBNF grammar or pass ignorecase=True at compilation time,  I find that the value is not carried through correctly to the Context object,  thus I have to do

mygrammar.parse(something,ignorecase=True)

which is close enough for rock and roll but does not match the documentation.

**Comment by apalala** [comment]
``@@ignorecase`` does no longer apply to patterns (regular expressions) in TatSu.

Could you post an example grammar of the failure you're experimenting (a unit test would be best).

**Comment by apalala** [comment]
Not reproducible.

**Comment by rejoc** [comment]
here is a way to reproduce

```
import tatsu
from tatsu.exceptions import FailedToken

grammar = """
@@grammar :: HP_BASIC

@@ignorecase :: True

start = line $;

line = up | down | left | right ;

up = d:'UP' ;
down = d:'DOWN' ;
left = d:'LEFT' ;
right = d:'RIGHT' ;
"""

parser = tatsu.compile(grammar, ignorecase=True)

for k in ('LEFT', 'RIGHT', 'down', 'DOWN'):
    try:
        print(parser.parse(k))
    except FailedToken as err:
        print('Error...')
        print(err)
        print('-----------------------------------')

print('The end...')
```

it will give
```
{'d': 'LEFT'}
{'d': 'RIGHT'}
Error...
(1:1) expecting 'UP' :
down
^
up
line
start
-----------------------------------
{'d': 'DOWN'}
The end...

```

where we should get
```
{'d': 'LEFT'}
{'d': 'RIGHT'}
{'d': 'DOWN'}
{'d': 'DOWN'}
The end...

```
