### ISSUE TITLE
NodeWalker._find_walker returns invalid walker due to conflicting ids in node.__class__.

### ISSUE THREAD

**Issue by by-Exist** [neogeny/TatSu#278]
The following code is inserted in the NodeWalker.walk method.
print(f"[{id(node.\_\_class__)}]", node.\_\_class__, walker.\_\_name__)

And I got the following result:
[1872727841376] <class 'tatsu.synth.Reference'> walk__reference
[1872727841376] <class 'tatsu.synth.Composite'> walk__reference

I could see that different Node Classes returned the same id.
I'm not good enough to edit the code of the tatsu library.
However, it was confirmed that the problem did not occur when changing the classid of \_find_walker from id(cls) to cls.\_\_name__.

**Comment by apalala** [comment]
I agree that relying on `id(node.__class__)` is unreliable, as the Python definition allows for it to be a reference to a reusable memory address.

Could you post a pull request ti fix the above?

**Comment by by-Exist** [comment]
> I agree that relying on `id(node.__class__)` is unreliable, as the Python definition allows for it to be a reference to a reusable memory address.
> 
> Could you post a pull request to fix the above?

In the process of compiling the grammar, we do not know how the Node class is generated or whether it is forbidden to define a Node with the same name in the grammar. So I think it's unsuitable for me to modify that code.

**Comment by apalala** [comment]
You can use `node.__class__.__qualname__` to avoid border cases, and proceed with the pull request.

https://peps.python.org/pep-3155/

Thanks!
