### ISSUE TITLE
Positive join cant ignore Whitespace

### ISSUE THREAD

**Issue by coalooball** [neogeny/TatSu#311]
Hi, I found that "Positive join" does not ignore whitespace characters when parsing text of list type. I carefully reviewed the official documentation, but did not find a further solution.

THE EBNF:
```ebnf
@@grammar::TheftUids

start
    =
    expression $
    ;

expression
    =
    | ~ ( DELIMITER ).{ DIGIT }+
    | ~ { DIGIT }+
    ;

DIGIT = /\d+/ ;

DELIMITER = /[^\w\s]/ ;
```

The generating command:
```sh
tatsu --outfile uids.py uids.ebnf
```

The testing Python snippet:

```python
from uids import TheftUidsParser

p = TheftUidsParser()

res = p.parse("""27321334942597129, 27345249320501258,
27368210215665668,
27795585241972917,
27897393146691585,
27897393146691586,
27977030430359552,
28068272705044481,
28068272705044482,
28068272705044483,
28068272705044484,
28068272705044485,
28068272705044486,
28068272705044487,
28068272705044488
"""
)

```

The OUTPUT
```sh
tatsu.exceptions.FailedCut: (1:19) Expecting <DIGIT> :
27321334942597129, 27345249320501258,
                  ^
DIGIT
expression
start
```

**Comment by coalooball** [comment]
The code using `DELIMITER = /[^\w\s]+/ ;`  has same error.

**Comment by coalooball** [comment]
I found an alternative solution:
```ebnf
DELIMITER = /[^\w\s]\s*/ ;
```

**Comment by dnicolodi** [comment]
Rule with names starting with a capital letter do not advance over white space before beginning to parse, thus the latter at least is expected behavior. See https://tatsu.readthedocs.io/en/stable/syntax.html#rules
