### ISSUE TITLE
Broken 3.1.9 wheel package

### ISSUE THREAD

**Issue by JITdev** [neogeny/TatSu#321]
I think there is something wrong with the build process, there are missing folders in the wheel package. 
It causes imports are missing eg. utils.

**Comment by dnicolodi** [comment]
3.1.9?

**Comment by apalala** [comment]
I can reproduce this with a simple test. The target version is 5.9.0.

**Comment by apalala** [comment]
Fixed in 5.9.1

**Comment by JITdev** [comment]
> 3.1.9?

Sorry, yes 5.9.0. Thank you for your quick fix!
