### ISSUE TITLE
TatSu installs the 'test' directrory into the global python namespace

### ISSUE THREAD

**Issue by yurivict** [neogeny/TatSu#333]
This causes conflicts:
```
pkg-static: py39-TatSu-5.11.2 conflicts with py39-sphinx-argparse-0.4.0 (installs files into the same place).  Problematic file: /usr/local/lib/python3.9/site-packages/test/__init__.py
```

**Comment by apalala** [comment]
TatSu should not install `test` anywhere.

This issue is probably the product of a mistake during the migration to `pyproject.toml`. 

A hint to what to fix or a pull request would be appreciated.

**Comment by yurivict** [comment]
Remove ```test``` [here](https://github.com/neogeny/TatSu/blob/master/pyproject.toml#L54C1-L54C55).

**Comment by apalala** [comment]
It seems that neither the `grammar` nor the `examples` directories should be part of the installation. They should only be part of source-code packages, which are controlled by `MANIFEST.in` for `setuptools`.
