### ISSUE TITLE
Need a minimal hello-tatsu test case; getting errors.

### ISSUE THREAD

**Issue by hariedo** [neogeny/TatSu#40]
I did not want to hijack another issue where they say more examples are required, but I agree with it.

I wanted to make a "hello tatsu" example to see if I could use it.  Right now, I created a file with nothing but one line in it:

```
hello.
```

If I create the test.ebnf file like this:
```
# test of Tatsu
source = sentence* $ ;
sentence = 'hello.' ;
```

I received the following error:
```
tatsu.exceptions.FailedRef: in(1:1) could not resolve reference to rule 'start' :
hello.
^
```

Okay, is "start" a reserved word for the top-most rule?  I changed the rule name "source" to "start" but that doesn't change anything.  Still get the same error.

Anyway, a walkthrough to introduce the workflow of using Tatsu would be welcome.

**Comment by hariedo** [comment]
Some operator error, in my example; I did not re-generate the test.py between attempts.  However, the overall point is valid.  The "start" name is not mentioned in the output test.py at all, nor in the usage text in the error. If you don't supply the STARTRULE, my expectation is for it to use the top rule in the grammar or something, not the magic word "start" which may not even exist in the grammar.

**Comment by apalala** [comment]
@hariedo You are right about the generated parsers expecting a _start_ rule.
