### ISSUE TITLE
Compiling grammar from command or lib does not yield the same result

### ISSUE THREAD

**Issue by fpom** [neogeny/TatSu#51]
I have a grammar with a directive `@@whitespace :: /[\t ]+/`. Then, if I use `tatsu.to_python_sourcecode`, it produces a code where the Buffer class is initialised with `whitespace='[\\t ]+'`. But, if I use `tastu` command, the code has `whitespace=re.compile('[\\t ]+')` instead.

I've encountered very weird parsing errors due to this, I presume that white space removal was eating a `t` at the beginning of a keyword called `trans` because the error was something like:

    ... expecting 'trans'
        trans ....
         ^

with white space before `trans` and the caret under the `r`.

**Comment by apalala** [comment]
@fpom Can you provide a unit test for this case?
