### ISSUE TITLE
File missing in pip install of the module

### ISSUE THREAD

**Issue by Ruth-Polymnia** [neogeny/TatSu#56]
The `g2e/antlr.ebnf` file is missing from the pip module `https://pypi.python.org/pypi/tatsu/4.2.5`.

**Comment by dtrckd** [comment]
The file is still missing in the current version (4.4.0) in the pip repository.

**Comment by apalala** [comment]
My apologies if this is so. I will publish an amended release ASAP, @dtrckd !

**Comment by g40** [comment]
And indeed remains missing. Would be nice to fix this for a better out of box experience. Many thanks,
