### ISSUE TITLE
calc example: parse_factored() fails against "1*2+3-4"

### ISSUE THREAD

**Issue by taotao54321** [neogeny/TatSu#57]
I played around with example/calc, and modified expressions in calc.py like below:

```
"3 + 5 * (10 - 20)" -> "1 * 2 + 3 - 4"
```

Then, calc.py failed on parse_factored(). Is this a problem of the grammer?

[Here](https://gist.github.com/taotao54321/5ac3f9b3c138b0a978aaedc63152d4fb) is the modified calc.py and error log.

### my environment

* Python 3.6.3
* tatsu 4.2.5

**Comment by apalala** [comment]
There are problems with left-recursive grammars, as described in issue #27. 

I haven't had time to work on the problem, so I may remove support for left recursion until I do.
