### ISSUE TITLE
Allow AST changes

### ISSUE THREAD

**Issue by dvdrndlph** [neogeny/TatSu#61]
I would like to make changes to an AST data structure after generating one. But such operations are not allowed. Is there a compelling reason for this? Could this be allowed via an option of some sort? Another approach would be a function to copy the AST into a analogous mutable data structure.

**Comment by apalala** [comment]
An instance of an `AST` can be changed by setting it's `_closed` property to `False`. ASTs are "closed" by default to avoid some very difficult to debug problems. It's usually better, when the logic allows it, to create a copy of the AST with something like `AST(prev_ast, myattr=new_value)`

**Comment by dvdrndlph** [comment]
I would say that if the setting the private instance variable is permissible, this should be signaled with a method for changing it.  I hesitate to change variables that start with an underscore, as these are not supposed to be part of the public interface.

Updating the data structure directly seems the most straightforward  approach, but I will investigate how I can make copies, as you suggest. A more detailed example for doing this would be appreciated.

Thanks again for a great tool.
