### ISSUE TITLE
Generated parser fails with "could not resolve reference to rule 'start'"

### ISSUE THREAD

**Issue by r-chaves** [neogeny/TatSu#62]
I am trying to use TatSu on a new project (after having used grako successfully on a previous project), but I am running into this issue. I have created a (hopefully) minimal test case that reproduces the same issue I am seeing; my actual grammar is more complex, but I don't think it is the issue.

# Setup
Python running in virtual environment:
```
Python 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
TatSu version: `TatSu==4.2.5`
Input grammar: [test.ebnf.txt](https://github.com/neogeny/TatSu/files/1783228/test.ebnf.txt)
Parser generated with `python -m tatsu test.ebnf.txt > test_parser.py`:
```
------------------------------------------------------------------------
          19  lines in grammar
           3  rules in grammar
          12  nodes in AST
```
# The issue
Below is the output when testing the parser with the input string `4 + 5` on stdin:
```
(py2env) ryan@mrecho ~/Developer/projects/tmp $ python test_parser.py
4+5
Traceback (most recent call last):
  File "test_parser.py", line 123, in <module>
    ast = generic_main(main, TESTParser, name='TEST')
  File "/Users/ryan/Developer/projects/py2env/lib/python2.7/site-packages/tatsu/util.py", line 338, in generic_main
    colorize=args.color
  File "test_parser.py", line 116, in main
    return parser.parse(text, start=start, filename=filename, **kwargs)
  File "/Users/ryan/Developer/projects/py2env/lib/python2.7/site-packages/tatsu/contexts.py", line 211, in parse
    raise self._furthest_exception
tatsu.exceptions.FailedRef: -(1:1) could not resolve reference to rule 'start' :
4 + 5
^
```
I get the same result and output when the input string `4 + 5` is placed in `test_input.txt` and run via `python test_parser.py test_input.txt`.

# Expected result
The expected result would what is output from the following short program:
```
def main():
    """
    Main script function.
    """
    with open(sys.argv[1], 'r') as grammar_file:
        grammar = grammar_file.read()

    with open(sys.argv[2], 'r') as input_file:
        input_text = input_file.read()

    model = tatsu.compile(grammar, trace=False)
    ast = model.parse(input_text, trace=False, colorize=True)
    print(tatsu.util.asjsons(ast))

if __name__ == "__main__":
    main()
```
Expected output:
```
[
  "4",
  "+",
  "5"
]
```

**Comment by r-chaves** [comment]
After some playing around, this appears to be due to two issues:

1. In `util.py`, `args.startrule` is assigned `None` in the call to `addarg` if it is not specified in the command-line arguments. This has the subsequent effect in `main` of the generated parser not assigning the grammar's first rule to to the kwarg `start`.
2. The generated parser's `main` calls `parser.parse` with the kwarg `start=start`. It's likely the intent was to use `rule_name=start` since this is an actual kwarg to `ParseContext.parse()`. This is the only use of the word/identifier `start` in `contexts.py`. 

Adjusting `utils.py` and the generated parser to account for these issues results in the expected output. I will submit a pull request for this.

**Comment by apalala** [comment]
Fixed by @r-chaves
