### ISSUE TITLE
Generated Python code doesn't cope with multi-line regexs

### ISSUE THREAD

**Issue by pdw-mb** [neogeny/TatSu#66]
Consider:

```
myrule = /(?x) 
   foo
   bar
/ $ ;
```
This generates:

```
self._pattern(r'(?x) \n   foo\n   bar\n')
```
Which will look for literal newlines in the string, rather than being ignored.

**Comment by apalala** [comment]
Interesting @pdw-mb! Would you submit the patch to fix this? (though fixing it may bring backwards-compatibility problems).

**Comment by pdw-mb** [comment]
I don't fully understand the existing code, which is always a bad place to start for fixing something!
```
raw_repr = 'r' + urepr(self.node.pattern).replace("\\\\", '\\')
```
I think the use of a raw string is problematic, as I don't think you can output a literal newline in such a string, and to work with "(?x)" regexs we need to preserve the difference between a literal newline and an escaped one.  

The following code appears to work for me:
```
raw_repr = urepr(self.node.pattern)
```
On the input:
```
myrule = /(?x)foo\nbar
blort/ $ ;
```
We now get:
```
self._pattern('(?x)foo\\nbar\nblort')
```
which correctly matches

```
foo
barblort
```

If we remove the (?x) it correctly matches:

```
foo
bar
blort
```
(both \n and a literal newline match a newline)
