### ISSUE TITLE
ModelBuilderSemantics Subclassing

### ISSUE THREAD

**Issue by Victorious3** [neogeny/TatSu#70]
```ebnf
start = expression $;

expression =
    | addition
    | subtraction
    | number;

addition::BinaryOp::Op = left:expression op:'+' ~ right:number;
subtraction::BinaryOp::Op = left:expression op:'-' ~ right:number;

number = /\d+/;
```
This triggers an exception: https://pastebin.com/raw/qMUUXEKb
It works when you remove `left:expression` in addition and subtraction

I'm not sure how this feature is supposed to work in the first place, how does it decide what to put on the base class and what on the inherited one? I suppose the workaround would be to create the base class manually and pass it to the `ModelBuilderSemantics` instance.

In either case, this should be documented better.

**Comment by apalala** [comment]
Python 3.7 is recent, and the semantics of metaclasses may have changed to better support typing. This case should be added as a unit test.

**Comment by Victorious3** [comment]
@apalala What's supposed to happen if there are multiple base classes?
```
rule2::A::B::C = c:();
```
Is B a subclass of C now, and A a subclass of B? 
Or does A inherit from B and C, and B is unrelated to C?

**Comment by apalala** [comment]
> @apalala What's supposed to happen if there are multiple base classes?
> 
> ```
> rule2::A::B::C = a:();
> ```
> Is B a subclass of C now, and A a subclass of B?
> Or does A inherit from B and C, and B is unrelated to C?

TasSu currently doesn't check that the inheritance tree makes sense. I guess the Python compiler will err if the generated Python is no good.
