### ISSUE TITLE
Subclassing wins over python style comment

### ISSUE THREAD

**Issue by Victorious3** [neogeny/TatSu#71]
```ebnf
start = expression $;

expression =
#    | addition
    | subtraction
    | number;

#addition::BinaryOp::Op = left:expression op:'+' ~ right:number;
subtraction::BinaryOp = left:expression op:'-' ~ right:number;

number = /\d+/;
```
Fails with: https://pastebin.com/raw/gzJwygGy

This however, works just fine;
```diff
+(*addition::BinaryOp::Op = left:expression op:'+' ~ right:number;*)
-#addition::BinaryOp::Op = left:expression op:'+' ~ right:number;
 subtraction::BinaryOp = left:expression op:'-' ~ right:number;
```

**Comment by apalala** [comment]
Python-style comments should be resolved at the lexical level, and never seen by the grammar. There's something else going on here.

**Comment by Victorious3** [comment]
It's caused by the Buffer not being lenient enough, `#addition::` looks like a pragma to it and the second `::` causes the tuple unpacking to fail.
