### ISSUE TITLE
Allow False as a value for @@whitespace

### ISSUE THREAD

**Issue by Victorious3** [neogeny/TatSu#73]
Currently using this inside my grammar:
```
@@whitespace :: /(?!)/
```
which doesn't match anything.
```
@@whitespace :: False
```
would be more descriptive and probably more performant. `True` would set it to the default value.
Alternatively it could accept a string and then convert it to a regex, just like it does when calling parse with `whitespace=...`

**Comment by apalala** [comment]
Interesting @Victorious3! I hadn't thought of languages with no whitespace. Maybe `@@whitespace :: None``?

**Comment by Victorious3** [comment]
Sure, that works as well.

**Comment by apalala** [comment]
Hey @Victorious3. Maybe the good fix is to allow `//` to mean `/(?!)/` throughout?
