### ISSUE TITLE
@@keyword confusion

### ISSUE THREAD

**Issue by Victorious3** [neogeny/TatSu#77]
This here is valid:
```
@@namechars :: '_'
@@keyword :: if else not and or false true var let type
```

But if you swap those two lines:
```
@@keyword :: if else not and or false true var let type
@@namechars :: '_'
```

It gives the following error:
```
no available options :
@@namechars :: '_'
 ^
decorator
rule
grammar
start
```

**Comment by Victorious3** [comment]
This is caused by the grammar wanting to have directives first, and then keywords. Letting them appear in any order should be a simple change

**Comment by Victorious3** [comment]
Furthermore, all directives need to be placed before any rule is parsed. This doesn't really matter in practice as I like to keep them there anyways, but imo it makes no sense to enforce this either.

**Comment by apalala** [comment]
Hy @Victorious3 ! Where's the patch to fix this? ;-)

**Comment by Victorious3** [comment]
@apalala It was easy enough to work around it once I've discovered what's going on :P
