### ISSUE TITLE
Help needed with a certain grammar

### ISSUE THREAD

**Issue by supriyo-biswas** [neogeny/TatSu#81]
I have the following grammar:

```
@@grammar :: Shell
start                    = word $;
word                     = squoted | dquoted | bareword;
squoted                  = /'[^']*'/;
identifier               = /[a-zA-Z_][a-zA-Z0-9_]*/;
variable                 = '$' ( ( identifier | '?') | '{' ( identifier | '?' ) '}');
commsub                  = '$(' word ')' | '`' word '`';
dquoted                  = '"' { ( commsub | variable | dquoted_nonspec ) }* '"';
dquoted_nonspec          = /(?:\\.|[^\\`])/;
bareword                 = { ( commsub | variable | bareword_nonspec) }*;
bareword_nonspec         = /(?:\\.|[^'"&\s()<>`|;#])/;
```
According to my understanding, the above rules should cause a string such as `"hello"` to be parsed as a set of `dquoted_nonspec` tokens.

However, on trying to parse `"hello"` with the above grammar, I get a FailedParse exception, since it seems tatsu only tries `commsub` and does not bother with checking if it is a `variable` or `dquoted_nonspec`.

```
tatsu.exceptions.FailedParse: (1:1) no available options :

^
commsub
dquoted
word
start
```

Am I doing something wrong here?

**Comment by Victorious3** [comment]
Your regex for `dquoted_nonspec` matches the closing quote, so it can never match `dquoted`.

I'm a bit irritated by your use of non capturing groups. If you want them to not appear in the resuling AST you have to use the [override operator](https://tatsu.readthedocs.io/en/stable/syntax.html#id19). Or better yet, name the parts that you need.

It could be a useful addition to make them behave as expected, however. Right now it only cares about the entire match so the use of non capturing groups will have no effect: https://github.com/neogeny/TatSu/blob/4aa9636ab1a77a24a5b60eeb06575aee5cf20dd7/tatsu/buffering.py#L322-L327

**Comment by supriyo-biswas** [comment]
Thanks for your help 😄 

The capturing groups are there because I had formed this grammar from some older source code I had. Anyway, just like you said, it doesn't matter because Tatsu only recognizes the entire match.
