### ISSUE TITLE
Unreasonably long exception traces

### ISSUE THREAD

**Issue by Victorious3** [neogeny/TatSu#85]
This is more of a quality of life change, and no priority.
Something I've noticed from reading several stack traces involving TatSu is that they always span several hundred lines, including re-raising with mostly useless information. This is due to a mixture of using exceptions for flow control, and the nature of recursive descent parsers that tend to call a lot of methods.

Since the entire stack trace is barely ever needed I would propose to suppress everything but the exception message at the top level (i.e the compile/parse functions) unless a flag is set.
Python 3 has

```python 
raise exception from None
```
but someone has probably backported this feature to support 2.7 as well.

Scala has a mixin `NoStackTrace` which prevents it from getting generated in the first place, if something like this exists from Python it could spare quite a bit of memory usage and some CPU time as well.

**Comment by Victorious3** [comment]
EDIT: It seems like `parse` already does this, but not in the generated parser.

**Comment by apalala** [comment]
The stack trace is useful for debugging, and easy to suppress with a `try/except`, don't you think? What does `re` do on different kinds of errors?

**Comment by apalala** [comment]
Programs using **TatSu** should `try: ... except: ParseException` to distinguish between parse errors and everything else. That is what **TatSu**'s own `tool.py` does ([see here](https://github.com/neogeny/TatSu/blob/master/tatsu/tool.py#L262)):
