### ISSUE TITLE
Better support for linters and documentation

### ISSUE THREAD

**Issue by Victorious3** [neogeny/TatSu#86]
All public facing API should have type information attached to it, and the usage should be documented in the source code.

**Comment by apalala** [comment]
Let's postpone this until we drop 2.7.

**Comment by Victorious3** [comment]
I'd volunteer to spend a night adding type annotations once 2.7 gets deprecated. 
I haven't looked into rst or python docs yet but I assume there's a way to automatically include them in the source code to avoid copy pasting documentation.

**Comment by apalala** [comment]
We should drop 2.7, except for bugs, on the upcoming release.

**Comment by Victorious3** [comment]
I'd make sure that left recursion makes it into the last 2.7 release (since it already works with it) so leave this one for after the next release?

**Comment by apalala** [comment]
This seems very outdated...
