### ISSUE TITLE
Recommendations for converting a project from ply to tatsu

### ISSUE THREAD

**Issue by Midnighter** [neogeny/TatSu#87]
I have a fairly [complex example](https://github.com/Midnighter/BRENDA-Parser/tree/refactor/lexer) of parsing some text data. It is currently based on [ply](http://www.dabeaz.com/ply/) and I'm finding it quite hard to debug.

I was wondering if you can give some general guidance regarding conversion of a project from ply to TatSu and whether you think it's worth it, where you see the (dis-)advantages. As you can tell I have never used tatsu before but it looks very promising.

Some of the features that I definitely need from ply:

* Setting precedence rules
* Nested contexts, i.e., different rules for token parsing inside of certain contexts
* Might need semantic actions although that probably depends on specific mechanics of tatsu

In the end I want to translate content from a flat file into database models.

**Comment by Midnighter** [comment]
Alright, thank you for your thoughts. I've played a bit with tatsu so far and some things definitely seemed easier than before. However, I'm having trouble converting rules that I got working into single choice rules such that I can add the node type to the rules and build a model. For example, I would like to parse the following content into one object:

```python
"""
PR\t#8# Homo sapiens P39462 UniProt
	<10,11,12,13,14,15,16,17,18,19,20,21,22,23,53,96,107,109,115,116,119
	124,150,180,186,191,194,206,228,229,273>
"""
```

A single rule could look like this:

```
protein
    =
    | protein '#' /\d+/ '#'
    | protein /([A-N,R-Z][0-9]([A-Z][A-Z, 0-9][A-Z, 0-9][0-9]){1,2})|([O,P,Q][0-9][A-Z, 0-9][A-Z, 0-9][A-Z, 0-9][0-9])(\.\d+)?/ ['SwissProt' | 'UniProt']
    | protein /\w+/ /\w+/
    | 'PR' &('#'  /\d+/ '#')
    ;
```

Please consider that every element besides `'PR'` is optional.

What I've been trying so far is:

```
@@grammar::Protein

start
    =
    protein $
    ;
    
protein
    =
    | protein_identification
    | protein_organism
    | protein_accession
    | protein_citation
    | 'PR' &('#' number '#')
    ;
    
protein_identification::ProteinIdentifier
    =
    left:protein '#' right:number '#'
    ;
    
protein_citation::Citation
    =
    left:protein right:('<' ','.{number}+ '>' {'<' ','.{number}+ '>'}*)
    ;
    
protein_accession::Accession
    =
    left:protein right:(/([A-N,R-Z][0-9]([A-Z][A-Z, 0-9][A-Z, 0-9][0-9]){1,2})|([O,P,Q][0-9][A-Z, 0-9][A-Z, 0-9][A-Z, 0-9][0-9])(\.\d+)?/ ['SwissProt' | 'UniProt'])
    ;
    
protein_organism::Organism
    =
    left:protein right:(content content)
    ;
    
content::str
    =
    /\w+/
    ;

number::int
    =
    /\d+/
    ;
```

but it fails miserably.

Can you give me any pointers on how to best accomplish this, please? I also appreciate any links to reading material.

**Comment by Victorious3** [comment]
I changed 
```
protein_citation::Citation =
    left:protein right: {'<' ','.{number}+ '>'}+ ;
``` 
Just a bit shorter. That huge regex in `protein_accession` is also bothering me a bit but I suppose it works (I tend to write these out using grammar rules for my own sake)

Then I added a missing comma in your input text and then it parses on my branch https://github.com/Victorious3/TatSu/
Your example uses left recursion, my PR that fixes it wasn't merged yet (I keep missing @apalala)

The AST I get:
```
AST({'left': AST({'left': AST({'left': AST({'left': 'PR', 'right': '8'}), 'right': ['Homo', 'sapiens']}), 'right': ['P39462', 'UniProt']}), 'right': [['<', ['10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '53', '96', '107', '109', '115', '116', '119', '124', '150', '180', '186', '191', '194', '206', '228', '229', '273'], '>']]})
```
looks about right?

Apart from that, I don't really see why it's necessary here, couldn't you do something like this?
```
protein = 'PR' { 
    | protein_identification
    | protein_organism
    | protein_accession
    | protein_citation 
}* ;
```
and then remove the left recursion entirely?

**Comment by Midnighter** [comment]
Thank you very much! I had a chance to install your branch and try your changes and I like them.

> That huge regex in protein_accession is also bothering me a bit but I suppose it works (I tend to write these out using grammar rules for my own sake)

I'm simply using the [official regular expression](https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000005) for those database identifiers.

> couldn't you do something like this

I'll play around with it a bit. What I need is `'PR'` without `'#' number '#'` should be an error and I want to skip or otherwise recover from that.

I also wanted separate rules in order to construct an object from that but I suppose I could use names instead. I'll try to give another example when I got a bit further. Still new to tatsu so you probably have a much better idea of how I can achieve what I want.

**Comment by apalala** [comment]
Solved from the OP's perspective, so closing.

**Comment by Midnighter** [comment]
So the branch that enables this functionality is merged?

**Comment by apalala** [comment]
It's merged, @Midnighter . There will be a release as soon as I can coordinate with @Victorious3 .
