### ISSUE TITLE
ModelBuilderSemantics doesn't include optional attributes

### ISSUE THREAD

**Issue by tudor** [neogeny/TatSu#89]
If I have a rule that with an optional named component, that component shows up as `None` when using the AST, but is missing from the model class when using `ModelBuilderSemantics`, see the code below:

```py
import tatsu
from tatsu.model import ModelBuilderSemantics

grammar = r"""
foo::Foo = left:identifier [ ':' right:identifier ] $ ;
identifier = /\w+/ ;
"""

grammar = tatsu.compile(grammar)

a = grammar.parse('foo : bar', semantics=ModelBuilderSemantics())
assert a.left == 'foo'
assert a.right == 'bar'

b = grammar.parse('foo', semantics=ModelBuilderSemantics())
assert b.left == 'foo'
assert b.right is None  # AttributeError: 'Foo' object has no attribute 'right'
```

**Comment by tudor** [comment]
Having to do `getattr(b, 'right', None)` for all optional fields is annoying.

**Comment by Victorious3** [comment]
I agree with that sentiment, there are other places in TatSu as well where this has bothered me, such as when rendering models...

What it does right now is just add everything it encounters as attributes to the Node instance: 
https://github.com/neogeny/TatSu/blob/7ddf6a95063f627148a77eaf7963a9271fa3c9b6/tatsu/objectmodel.py#L41-L45

This is true for both synthesized classes and for when you go ahead and generate the python code with `tatsu --object-model`. The easiest "fix" would be to get Model to return `None` on attributes it doesn't know, but I don't feel very good about that as it gets rid of the destinction of "attribute doesn't exist" and "attribute is left empty". It might even break some assumptions.

The other way would be to radically change the way `tatsu.synth` works, as well as generating constructors for the generated object model that set all unset attributes to `None`.

Sadly I don't have any other solution for you right now. If this is bothersome enough to you, you can create a PR with the changes required, but be prepared to pour a substantial amount of effort into it. Ultimately I don't think the added convenience justifies making that change for now.

### Addendum:

Sometimes there are ways around this using the grammar to explicitly insert `None` into the AST:
```
start::Node = [attr: "0"] $;
```
This leaves out `attr` entirely when `0` is not getting encountered, however
```
start::Node = attr: ["0"] $;
```
This will either be `0` or `None`

Using this, by splitting your rules up and using the `@` operator you can probably create the intended behavior. Feel free to decide for yourself if this is less effort than writing `getattr`.

Another way around this would be to add your own baste type to `ModelBuilderSemantics` that returns `None` for unset attributes.

**Comment by apalala** [comment]
I don't object to qualifying this annoying omission as a bug. Anyone care to submit a PR for a patch?

**Comment by apalala** [comment]
If you look at the Python code generator, there are provisions for recovering _all_ the mentioned attributes there. It should be easy to generalize the strategy to all of TatSu.
