### ISSUE TITLE
Colorized output broken on windows

### ISSUE THREAD

**Issue by Nitrogenycs** [neogeny/TatSu#93]
As the title says, running tatsu in cli mode with "--color" or passing "colorize=True" to e.g. parser.parse() causes garbled output to be produced. The color control characters appear literally.
If I manually init colorama and print something myself colors for my test output will show up, but colors output by tatsu still appear as garbled characters.
I suspect there's something problematic with the integration of trace events and logging that's used to output traces.

**Comment by apalala** [comment]
Hello @Nitrogenycs. Please provide the platform, operating system version, and command shell used.

**Comment by Nitrogenycs** [comment]
Python 3.6.4 64-bit, Windows 10, default cmd.exe shell

**Comment by Victorious3** [comment]
I've had my issues with the color output before, I think it comes from Tatsu not calling `colorama.init()`. I wanted to fix that at some point but got sidetracked.

**Comment by apalala** [comment]
Could the OP check if calling `colorama.init()` fixes the problems (and perhaps submit a pull request)?
