### ISSUE TITLE
Left recursion bug when not at top level?

### ISSUE THREAD

**Issue by tudor** [neogeny/TatSu#94]
I have the following grammar that purports to parse declarations of the form: `<type> <name>`. The `type` is either an identifier, or an array of `type`, so `int x` and `int[] x` and `int[][] x` would be valid declarations.

```py
import tatsu

grammar = r"""
identifier = /\w+/ ;

type = (vector_type | leaf_type) ;
vector_type = base:type '[]' ;
leaf_type = id:identifier ;

decl = type:type name:identifier ;
"""

print(tatsu.parse(grammar, 'int x', start='decl'))
```

Yet when I try to parse `int x`, I get:

```
tatsu.exceptions.FailedToken: (1:1) expecting '[]' :

^
vector_type
type
decl
```

`int[] x` works fine, and so does `int` if parsed at the top level (`start='type'`). I'm using TatSu 4.3.0.

**Comment by tudor** [comment]
I don't know much about TatSu's internals, but I wonder if this is related to https://github.com/neogeny/TatSu/issues/69 (@Victorious3 ?) in that TatSu doesn't realize that the `decl` rule is left-recursive.

**Comment by Victorious3** [comment]
It probably is, feel free to use my branch https://github.com/Victorious3/TatSu/tree/master for the time being until #75 is merged.
