### ISSUE TITLE
@@nameguard not honored in simple grammar

### ISSUE THREAD

**Issue by dvdrndlph** [neogeny/TatSu#95]
I am puzzled by this behavior:

```
from pprint import pprint
from tatsu import parse

GRAMMAR = """
sequence = {fingering}+ ;
fingering = '1' | '2' | '3' | '4' | '5' | 'x' ;
"""

test = "22"
ast = parse(GRAMMAR, test)
pprint(ast)  # Prints ['2', '2']

test = "xx"
ast = parse(GRAMMAR, test)
pprint(ast)  # tatsu.exceptions.FailedParse: (1:1) no available options :
```

Setting the grammar to the following works as expected:

```
GRAMMAR = """
sequence = {fingering}+ ;
fingering = /[1-5x]/ ; 
"""
```

Am I missing something?

**Comment by Victorious3** [comment]
You either have to tell the parser what rule to start with or name it "start".
I'm not sure why the other one works in the first place. There's also `$` to specify the end of input, I'd add that to your starting rule.

**Comment by apalala** [comment]
These are questions better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tatsu).

You probably need to check interactions with [@@nameguard](https://tatsu.readthedocs.io/en/stable/syntax.html#text-or-text), which is turned on by default.

**Comment by apalala** [comment]
Confirmed that the results is unexpected even with `@@nameguard :: False`

**Comment by dvdrndlph** [comment]
Thanks for the quick turnaround. I learned a lot.
